### PR TITLE
Merge: Flagsmith docker image version bump

### PR DESCRIPTION
**Pull request by dabeeeenster**
Automated PR generated by a release event in https://github.com/Flagsmith/flagsmith

### CODE REVIEW

**Comment by levrik** [comment]
Is there any reason for these PR being merged very rarely? Is it expected from users to bump version themself?

**Comment by matthewelwell** [comment]
Hi @levrik , these PRs are auto generated and are intended to update the default version whenever a new version is released. Unfortunately, it's hard to keep up with merging them. 

In general, yes - it is expected that users maintain the version themselves and these PRs are only to update the default value for new installations via helm.

**Comment by levrik** [comment]
@matthewelwell Thanks for the response. I depended on the updated Chart for upgrading Flagsmith so far as I wasn't sure if them not being merged simply means that a release isn't considered stable yet.

Would it be possible to add a central way to update the image tag to the Chart? It's easy to forget updating the `tag` inside both `api.image` and `frontend.image`.

**Comment by matthewelwell** [comment]
@levrik feel free to open an issue for this and/or submit a PR. Thanks!

**Pull request closed without merging**
