### PR TITLE
feat: add env variables from secrets

### PR DESCRIPTION
**Pull request by agarat**
Thanks for submitting a PR! Please check the boxes below:

- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have bumped the version number in `/charts/flagsmith/Chart.yaml` in the section `version`

## Changes

Some environment variables are sensitive (for example, Sendgrid API Key). In our environments we manage secrets separatedly from the helm charts. With this change, we will be able to create secrets and reference them as environment variables in the Flagsmith API and Frontend deployments.

### Adding extra environment variables from secrets
If you have existing secrets that you want to load as environment variables in either the API or the frontend deployments, add them in your `values.yaml` file under `api` or `frontend` as in the following example:
```
api:
  ...
  extraEnvFromSecret:
    MY_ENV_VARIABLE:
      secretName: mysecretname
      secretKey: mysecretkey
    MY_OTHER_VARIABLE:
      secretName: anothersecretname
      secretKey: anothersecretkey
```
## How did you test this code?

I ran `helm template flagsmith . -f values.yaml` and inspected the resulting templates. I verified that the environment variables were added.

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Hi @agarat - thanks so much for the PR. Would you be able to add some short documentation (just a couple of lines) that we can include in the docs? An example of how you would use it would be great. Thanks!

**Comment by agarat** [comment]
@dabeeeenster I just updated the PR comment to add the usage. Is something like that what you were looking for?
I'm not sure why the CI failed, but I think is unrelated to the changes I made.

**Comment by dabeeeenster** [comment]
Great thanks. Yep the issue is node/npm related - we'll look into this separately - thanks again!

**Comment by dabeeeenster** [comment]
Hi Sorry - we dropped this one - can you try merging from `Release 0.10.0` PR - that should fix the linter?

**Comment by dabeeeenster** [comment]
Great thanks @agarat  - we will get this merged in soon

**Comment by agarat** [comment]
Should I merge from main and bump this to `0.10.1`?

**Pull request merged**
