### PR TITLE
Added extraEnv for taskProcessor service

### LINKED ISSUE #168: Add `extraEnv` for taskProcessor service
Similar to the `extraEnv` attribute defined for the `api` service (see [here](https://docs.flagsmith.com/deployment/hosting/kubernetes#environment-variables)), it should be possible to define `extraEnv` for the taskProcessor service. 

We may need to consider how this affects current users of the charts, however, since the current behaviour is that the `api.extraEnv` gets written to the environment variables of the taskProcessor. Initially we should maintain this behaviour and write both `api.extraEnv` and `taskProcessor.extraEnv` to the taskProcessor environment variables but ideally we would deprecate the `api.extraEnv` from being used by the taskProcessor service.

### PR DESCRIPTION
**Pull request by Arvind644**
Fixes #168

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Please can you bump the version number here too

**Review by khvn26 — CHANGES_REQUESTED** [review]
Hello and thank you for your contribution. Unfortunately, we can't approve it just yet.

A change to default values isn't enough for the intended behaviour to work. You need to modify the `deployment-task-processor` template to support the new key. Additionally, you will need to implement the logic that will merge values from `api.extraEnv` and `taskProcessor.extraEnv` to support backwards compatibility.

Please let us know if you have any questions!

**Comment by matthewelwell** [comment]
Hi @Arvind644 , just checking if this is something that you're still working on?

**Comment by Arvind644** [comment]
@matthewelwell @khvn26  yeah I forget to commit changes. I just added a new commit. Can you review that.

**Review by khvn26 — APPROVED** [review]
Sorry for the late review — this looks good to me 👍

**Review by gagantrivedi — APPROVED** [review]

**Pull request merged**
