### PR TITLE
Fix secretKeyRef typo

### PR DESCRIPTION
**Pull request by dreglad**
Should be `key` instead of `name`

### CODE REVIEW

**Comment by dabeeeenster** [comment]
Thanks for this PR - please can you bump the version number to `0.2.15` then I can merge!

**Comment by dreglad** [comment]
Sure, done in commit 524571f5c997d4cda05fb2c92d27db30fe030c69

**Comment by dabeeeenster** [comment]
The builds are failing?

**Comment by dreglad** [comment]
> The builds are failing?

 https://github.com/Flagsmith/flagsmith-charts/pull/37/checks?check_run_id=3018151692#step:9:324
> `0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.`to 

Sounds to me like a flaky test failing due to a rest runner being unable to schedule some pod. manually retrying the job?

**Comment by dabeeeenster** [comment]
Yes that's what I thought, but I've retried the pipeline several times and it still fails.

**Comment by dreglad** [comment]
> Yes that's what I thought, but I've retried the pipeline several times and it still fails.

Even if I change nothing but the version number, the test still fails.  so maybe there is a failing dependency, not the chart itself.

**Comment by dabeeeenster** [comment]
OK I fixed it by bumping the action version in another PR - should be good to go with the latest version now

**Comment by dabeeeenster** [comment]
Thanks for the help!

**Pull request closed without merging**
